[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["-C", "default-linker-libraries"] # workaround https://github.com/esp-rs/embuild/issues/16

[unstable]
build-std = ["std", "panic_abort"]