[package]
name = "eap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dummycert = {path = "../dummycert"}
binrw = "0.10.0"
md5 = "0.7.0"
rand = "0.8.5"
rustls = "0.20.8"
rustls-pemfile = "1.0.2"